NoteFood.Web/Models/Dominio/Alimento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NoteFood.Web.Models.Dominio
{
    public class Alimento
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Porcao { get; set; }
        public float ValorPorcao { get; set; }
        public int Sub_Grupo_Id { get; set; }
    }
}

NoteFood.Web/Models/Dominio/AlimentoSelecionado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NoteFood.Web.Models.Dominio
{
    public class AlimentoSelecionado
    {
        public int Alimento_Id { get; set; }
        public int Qtd { get; set; }
    }
}

NoteFood.Web/Models/Dominio/SubGrupo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NoteFood.Web.Models.Dominio
{
    public class SubGrupo
    {
        public int SubId { get; set; }
        public string Nome { get; set; }

        public List<Alimento> Alimentos { get; set; }
    }
}

NoteFood.Web/Models/ViewModel/AlimentoCadastroViewModel.cs
using NoteFood.Web.Models.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoteFood.Web.Models.ViewModel
{
    public class AlimentoCadastroViewModel : Alimento
    {
        public SelectList ListaSubGrupos { get; set; }
    }
}

NoteFood.Web/Controllers/AlimentosController.cs
using NoteFood.Web.Models.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using NoteFood.Web.Models.ViewModel;

namespace NoteFood.Web.Controllers
{
    public class AlimentosController : Controller
    {
        private const string CONEXAO = "Server=localhost;Database=notefood;Uid=root;Pwd=paulodb;";

        private MySqlConnection Conectar()
        {
            MySqlConnection conn = new MySqlConnection(CONEXAO);
            conn.Open();
            return conn;
        }

        public ActionResult Index()
        {
            var conn = Conectar();
            MySqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT ID, NOME, DESCRICAO, PORCAO, VALORPORCAO, SUB_GRUPO_ID FROM ALIMENTO ;";

            List<Alimento> alimentos = new List<Alimento>();

            // Ler para preencher a lista de alimentos
            MySqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                Alimento alimento = new Alimento();
                alimento.Id = Convert.ToInt32(reader["ID"]);
                alimento.Nome = reader["NOME"].ToString();
                alimento.Descricao = (reader["DESCRICAO"] != DBNull.Value) ? reader["DESCRICAO"].ToString() : string.Empty;
                alimento.Porcao = reader["PORCAO"].ToString();
                alimento.ValorPorcao = Convert.ToInt32(reader["VALORPORCAO"]);
                alimento.Sub_Grupo_Id = Convert.ToInt32(reader["SUB_GRUPO_ID"]);
                 
                alimentos.Add(alimento);
            }

            conn.Close();

            return View(alimentos);
        }

        [HttpPost]
        public JsonResult RegistrarAlimentoSelecionado(AlimentoSelecionado alimentoSelecionado)
        {
            var conn = Conectar();
            var cmd = conn.CreateCommand();
            cmd.CommandText = "INSERT INTO ALIMENTO_SELECIONADO (ALIMENTO_ID, QTD) VALUES (@ALIMENTO_ID, @QTD);";
            cmd.Parameters.AddWithValue("@ALIMENTO_ID", alimentoSelecionado.Alimento_Id);
            cmd.Parameters.AddWithValue("@QTD", alimentoSelecionado.Qtd);
            cmd.ExecuteNonQuery();
            conn.Close();
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

NoteFood.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoteFood.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

NoteFood.Web/Views/Alimentos/Index.cshtml
@using NoteFood.Web.Models.Dominio
@model List<Alimento>
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div>
    @foreach (Alimento objAlimento in Model)
    {
        <div class="alimento">
            <img src="~/Assets/Imagens/Alimentos/@(objAlimento.Id).jpg" />
            <div>
                Nome:@objAlimento.Nome
            </div>
            <div>
                Descrição: @objAlimento.Descricao
            </div>
            <div>
                <input type="number" class="qtd" data-alimento-id="@objAlimento.Id" />
                <button type="button" class="btnAddQtd" onclick="registrarQtdAlimentos(@objAlimento.Id, this)">Adicionar</button>
            </div>
        </div>
    }
</div>

NoteFood.Web/Views/Home/Index.cshtml
@{ 
    Layout = "~/Views/_Layout.cshtml";
}
<div>
    Boas vindas, meu amigo!
</div>

NoteFood.Web/Views/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="~/Assets/global.css" rel="stylesheet" />
</head>
<body>
    <nav id="menu">
        <ul>
            <li>
                <!-- HTML PURO -->
                <a href="/Home">HOME</a>                
            </li>
            <li>
                <!-- ACTION LINK -->
                @Html.ActionLink("ALIMENTOS", "Index", "Alimentos")
            </li>
        </ul>
    </nav>
    <div id="conteudo">
        @RenderBody()
    </div>

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
    <script src="~/Assets/Scripts/Alimento.js"></script>
</body>
</html>